import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import styles from "./page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
